export const COVER = require('./cover.jpg')
export const LOGO = require('./landing2W.png')
export const LOGOB = require('./landing2.png')
export const SLOGO = require('./score.jpg')
export const TLOGO = require('./trunks2.png')
export const MAPMARKER = require('./mapMarker1.png')